# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
default:
  image: ruby:2.7.6-alpine3.15
  tags:
    - agarg-public-projects

stages:
  - test

test:
  stage: test
  before_script:
    - apk add --update-cache --virtual tcelfer-deps build-base sqlite-dev
    - ruby -v
    - bundle config set path vendor
    - bundle install -j 2
  script:
    - bundle exec rake
