Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
  - tcelfer.gemspec

AllCops:
  Exclude:
      - 'tmp/*'
      - 'vendor/**/*'
      - 'vendor/**/.*'
  TargetRubyVersion: 2.7

# These are new in Rubocop 0.80.0
# Which now will start introducing things in this manor
# see https://github.com/rubocop-hq/rubocop/issues/7731 for more info
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

# Rubocop 0.81.0
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

# Rubocop 0.82.0
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true

# Rubocop 0.83.0
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true

# Rubocop 0.84.0
Lint/DeprecatedOpenSSLConstant:
  Enabled: true

# Rubocop 0.85.0
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
